log_dir: "./experiments/kmflow_re1000_rs256_ddim_recons_conditional_log"

data:
    dataset: "kmflow"
    category: "kmflow"
    image_size: 256
    channels: 3
    num_workers: 4
    data_dir: "./data/kf_2d_re1000_256_40seed.npy"
    sample_data_dir: "./data/kmflow_sampled_data_irregnew.npz"
    stat_path: "./pretrained_weights/km256_stats.npz"
    data_kw: 'u3232'
    smoothing: True
    smoothing_scale: 7

model:
    type: "conditional"
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [ 1, 1, 1, 2 ]
    num_res_blocks: 1
    attn_resolutions: [ 16, ]
    dropout: 0.0
    var_type: fixedlarge
    ema_rate: 0.9999
    ema: True
    resamp_with_conv: True
    ckpt_path: "./pretrained_weights/conditional_ckpt_new.pth"

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 20
    last_only: True
    guidance_weight: 0.
    log_loss: True
    dump_arr: True